# Generated by Django 4.1.5 on 2023-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpage',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='authpage',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='authpage',
            name='user_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='authpage',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='authpage',
            name='user_pass',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
