# Generated by Django 4.1.5 on 2023-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0003_remove_authpage_first_name_remove_authpage_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpage',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
