# Generated by Django 4.1.5 on 2023-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0004_authpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpage',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='authpage',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
