# Generated by Django 4.1.5 on 2023-04-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0005_authpage_first_name_authpage_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authpage',
            old_name='first_name',
            new_name='your_name',
        ),
    ]
