# Generated by Django 4.1.5 on 2023-04-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0006_rename_first_name_authpage_your_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authpage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='authpage',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='authpage',
            name='user_pass',
        ),
        migrations.RemoveField(
            model_name='authpage',
            name='your_name',
        ),
    ]
